### ISSUE TITLE
Feature Request: Ability to easily switch between Search and Replace inputs

### ISSUE THREAD

**Issue by kevintraver** [chrisgrieser/nvim-rip-substitute#1]
### Checklist

- [X] I have read the README.
- [X] The feature would be useful to more users than just me.

### Feature Requested

It would be useful to have a function to easily switch between **_Search_** and **_Replace_** inputs.

This could then be mapped by the user to something like `<tab>`.

**Comment by chrisgrieser** [comment]
What do you mean by that? Simply switching search and replace lines? Not sure what the use case would be, but that would just be `ddp`. 

Or do you mean sth else?

**Comment by kevintraver** [comment]
Right now when you open the popup, it starts in _insert_ mode in the **_Search_** Input.  Then to switch to to the **_Replace_** input, you have to escape, and then move (`j`) to the **_Replace_** input.

I was hoping to have something like `tab`, where you could switch between the **_Search_** Input and **_Replace_** input without leaving insert mode.

**Comment by chrisgrieser** [comment]
I dunno. Arrow-down and arrow-up would cover this already (which can be remapped of course). Having that on one hotkey feels a bit too niche to add to the plugin.  

Nonetheless, you can create a function that does what you want with 2-3 lines of code and map it to the file type `rip-substitute`.

**Comment by kevintraver** [comment]
I threw together a draft [PR](https://github.com/chrisgrieser/nvim-rip-substitute/pull/2) if you wanted to check it out, because I think it might be useful. If you still don't want to use it, no worries I can add it to my own config!

**Comment by kevintraver** [comment]
I also made added to where it remembers cursor position when switching between inputs.

**Comment by kevintraver** [comment]
Just for reference, here is what I ended up doing

```lua
{
    "<tab>",
    mode = { "n", "i" },
    function()
      --- @class RipSubstituteState
      --- @field cursorPositions table<number, number>
      local state = require("rip-substitute.state").state
      if state.cursorPositions == nil then
        state.cursorPositions = { [1] = 0, [2] = 0 }
      end
      local cursorPos = vim.api.nvim_win_get_cursor(state.popupWinNr)
      state.cursorPositions[cursorPos[1]] = cursorPos[2]
      local line = cursorPos[1] == 1 and 2 or 1
      local col = state.cursorPositions[line] or 0
      vim.api.nvim_win_set_cursor(state.popupWinNr, { line, col })
    end,
    ft = "rip-substitute",
  }
```

Demo using the `<tab>` key to between **_Search_** and **_Replace_**, while remembering position

![out](https://github.com/chrisgrieser/nvim-rip-substitute/assets/196406/d0caa35b-25db-429a-b365-093e161b08e9)
