### ISSUE TITLE
Feature Request: String literal mode

### ISSUE THREAD

**Issue by Ajaymamtora** [chrisgrieser/nvim-rip-substitute#16]
### Checklist

- [X] I have read the README.
- [X] The feature would be useful to more users than just me.

### Feature Requested

Can you add support for toggling "--fixed-strings" as a flag to RG? I implemented it in my fork but it's really out of date and the merge is horrible

You could display a regex icon in the buffer title which indicates mode (also part of my fork)

I could do a PR if not

![image](https://github.com/user-attachments/assets/8b0a4cfb-9f45-4bcd-bd3b-228a02621225)

**Comment by chrisgrieser** [comment]
Eh, I am quite super swamped with work (and I maintain way to many plugins anyway…), so a PR is welcome, yeah
