### ISSUE TITLE
Bug: Sometimes line endings are incorrect

### ISSUE THREAD

**Issue by Ajaymamtora** [chrisgrieser/nvim-rip-substitute#17]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.

### Bug Description

When doing a replace I get "^M" at the end of each line which indicates incorrect line endings but it's inconsistent.

### To Reproduce

Edit file with windows ending on a unix device, replace text, sometimes get ^M at line end.

Could do something like this:
```lua
	local fileformat = vim.bo.fileformat
	if fileformat == "dos" then vim.list_extend(args, {
		"--crlf",
	}) end
```

### neovim version

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

### ripgrep version

ripgrep 14.1.0

features:-simd-accel,+pcre2
simd(compile):+NEON
simd(runtime):+NEON

PCRE2 10.42 is available (JIT is available)

### Minimal reproducible config

```lua
-
```

**Comment by chrisgrieser** [comment]
To be frank, I haven't touched a Windows device in decades, so I am not super familiar with such line endings issues. But if you have a working fix, feel free to open a PR for it.

**Comment by chrisgrieser** [comment]
Anyway, reading up the rg manpage on `--crlf`, looks like a safe addition. So if that fixes it on your end, I'm fine adding it without being able to reproduce it myself.
