### ISSUE TITLE
Feature Request: is it possible to prefill the replace line with the visual selection?

### ISSUE THREAD

**Issue by mikavilpas** [chrisgrieser/nvim-rip-substitute#21]
### Checklist

- [X] I have read the README.
- [X] The feature would be useful to more users than just me.

### Feature Requested

When I have a visual selection and I start nvim-rip-substitute, I see the selected text prefilled on the first line of the plugin's popup. The second line (the text to replace with) is empty.

However, often I want to make a minor modification to the selection, for example to fix a typo.

Would it be possible, for example, to prefill the second line with the text I already selected? 

### Relevant Screenshot

![image](https://github.com/user-attachments/assets/1774840f-79ef-4a2b-9f07-b71a8c1ac02c)

Notice that in this example I have the first line be escaped, but the second line cannot be escaped.

**Comment by chrisgrieser** [comment]
good idea, added as opt-in option: `prefill.alsoPrefillReplaceLine`
