### ISSUE TITLE
Bug: Crashes on `nt` mode with filetype `toggleterm`

### ISSUE THREAD

**Issue by sharpchen** [chrisgrieser/nvim-rip-substitute#22]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.

### Bug Description

Crashes on `nt` mode with filetype `toggleterm` for accidental hit

EDIT: can be solved by autocmd though, I am not sure does it make any sense to subsitute on nt mode?

### Relevant Screenshot

![image](https://github.com/user-attachments/assets/9dff6520-0c82-4f7b-8c10-f559a7f482bc)

### To Reproduce

1. open a toggleterm
2. scroll to enter nt mode
3. hit the keymap of raise rip-substitute
4. see error

### neovim version

NVIM v0.10.0

### ripgrep version

ripgrep 14.1.0

### Minimal reproducible config

```lua
local spec = {
  {
    'chrisgrieser/nvim-rip-substitute',
    cmd = 'RipSubstitute',
    keys = {
      {
        '\\',
        function()
          require('rip-substitute').sub()
        end,
        mode = { 'n', 'x' },
        desc = ' rip substitute',
      },
    },
    opts = {
      popupWin = {
        matchCountHlGroup = '@variable.parameter',
        noMatchHlGroup = '@variable.member',
        position = 'top',
        hideSearchReplaceLabels = true,
        border = 'rounded',
      },
      keymaps = { -- normal & visual mode, if not stated otherwise
        prevSubst = '<C-p>',
        nextSubst = '<C-n>',
      },
    },
  },
  {
    'akinsho/toggleterm.nvim',
    version = '*',
    init = function() end,
    config = function()
      require('toggleterm').setup({
        start_in_insert = true,
        direction = 'float',
        float_opts = {
          border = 'rounded',
        },
      })
    end,
  },
}

--------------------------------------------------------------------------------
vim.env.LAZY_STDPATH = "./nvim-repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
require("lazy.minit").repro { spec = spec }
```

**Comment by chrisgrieser** [comment]
Weird, the popup works for me, but it fails only later on, cause a terminal buffer is simply not writable.

Anyway, I added a check to prevent rip-substitute from running in non-modifiable buffers, so this should be fixed.
