### ISSUE TITLE
Can the :RipSubstitute command be used for inline find AND replace?

### ISSUE THREAD

**Issue by YousufSSyed** [chrisgrieser/nvim-rip-substitute#23]
### Checklist

- [X] I have read the README.
- [X] The feature would be useful to more users than just me.

### Feature Requested

I would like to use the command to completely replacing `:s` but there isn't documentation on how to do so. It doesn't work when I put the find and replace patterns in " quotes like I would with ripgrep on the command line.

**Comment by chrisgrieser** [comment]
Find and replace is what the plugin is doing. You don't need any quotes. 

So I basically don't understand what the request is.

**Comment by YousufSSyed** [comment]
For instance, I couldn't figure out how to use `:RipSubstitute` to do a find: `(^\s*?- )\[.\]`, and replace: `$1[x]`, without opening the find & replace menu:

```md
- [ ] task
```

**Comment by chrisgrieser** [comment]
Please try to explain your problem better. I read both of your messages three times and was still not able to understand what the problem is.

**Comment by YousufSSyed** [comment]
Ok, I want to specify both the find and replace patterns in the `:RipSubstitute` command to do the replace immediately. When I try `:.RipSubstitute (^\s*?- )\[.\] $1[x]` it just puts both patterns in the UI.

Does that make more sense?

**Comment by chrisgrieser** [comment]
Yes. See the edited reply above. That's not what the plugin has been made for. 

You also don't need to, since there are plenty of methods for doing so already.

**Comment by YousufSSyed** [comment]
Any options with ripgrep or modern regex?

**Comment by chrisgrieser** [comment]
E.g. https://github.com/chmln/sd
