### ISSUE TITLE
Bug: Handle `rg` installations not being built with pcre2 supports

### ISSUE THREAD

**Issue by niuiic** [chrisgrieser/nvim-rip-substitute#3]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.

### Bug Description

Required feature `pcre2` is not included in the ripgrep installed with `cargo`.

You may add this to the document, or maybe we can make this optional.

`cargo install ripgrep --features 'pcre2'`

### To Reproduce

x

### neovim version

```Text
0.10.0
```

**Comment by chrisgrieser** [comment]
I see, wasn't aware that rg does not always ship with pcre2 support. Do you by any chance know if there is a way to tell from an `rg` installation whether pcre2 is available? Ideally, I'd like to automatically detect whether to turn on pcre2 or not.

**Comment by niuiic** [comment]
Error msg from rg command told me this feature is missing. I just debuged the source code, and see this.

**Comment by chrisgrieser** [comment]
Found this in the man page: 

>        --pcre2-version
>          When this flag is present, ripgrep will print the version of PCRE2 in use, along with other
>          information, and then exit. If PCRE2 is not available, then ripgrep will print an error message
>          and exit with an error code.

Could you, just to be sure, tell me what `rg --pcre2-version` outputs on your system where rg has not pcre2 included?

**Comment by niuiic** [comment]
PCRE2 is not available in this build of ripgrep

**Comment by chrisgrieser** [comment]
exit code is 1, I presume?

**Comment by chrisgrieser** [comment]
Got it, added some validation that automatically turns of pcre2 if using a rg version without it, and also added some information to the readme
