### ISSUE TITLE
Bug: Command RipSubstitute not found after loading nvim-rip-substitute

### ISSUE THREAD

**Issue by Oneechan69** [chrisgrieser/nvim-rip-substitute#30]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.

### Bug Description

I get the notification "Command RipSubstitute not found after loading nvim-rip-substitute" whenever I try `:RipSubstitute`, it won't open at all for some reason.

### To Reproduce

1. Use the repro for `init.lua`
2. Launch nvim
3. `:RipSubstitute`

### Sample Text

N/A

### neovim version

```
NVIM v0.10.3
Build type: Release
LuaJIT 2.1.1734355927
Run "nvim -V1 -v" for more info
```

### ripgrep version

```
ripgrep 14.1.1
features:+pcre2
simd(compile):+NEON
simd(runtime):+NEON
PCRE2 10.43 is available (JIT is available)
```

### Minimal reproducible config

```lua
-- LazyNvim Setup
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
vim.opt.clipboard = "unnamedplus"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    "chrisgrieser/nvim-rip-substitute",
    cmd = "RipSubstitute",
    keys = {
      {
        "<leader>fs",
        function() require("rip-substitute").sub() end,
        mode = { "n", "x" },
        desc = " rip substitute",
      },
    },
  },
})
```

**Comment by chrisgrieser** [comment]
Thanks, fixed.

**Comment by Oneechan69** [comment]
I just came back because I forgot to mention that I reinstalled the plugin.

I updated it now and its fixed. That was quite, good shit!
