### ISSUE TITLE
Feature Request: config popup win postion

### ISSUE THREAD

**Issue by lei4519** [chrisgrieser/nvim-rip-substitute#4]
### Checklist

- [X] I have read the README.
- [X] The feature would be useful to more users than just me.

### Feature Requested

It may be more ergonomic to place the popup at the top right, like vscode. 

<img width="869" alt="image" src="https://github.com/chrisgrieser/nvim-rip-substitute/assets/38270410/26310c48-2c72-4aed-b2bd-7a7c7139bdc0">

On a large screen this makes it more natural to look at the input and match results without having to look away too much (and twist your neck), perhaps adding a configuration option to select the location of the pop-up window

**Comment by chrisgrieser** [comment]
implemented as option 👍
