### ISSUE TITLE
Bug: No match found

### ISSUE THREAD

**Issue by c30ra** [chrisgrieser/nvim-rip-substitute#8]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.

### Bug Description

When type in the popup the regex no matches are found

### Relevant Screenshot

![Schermata_20240629_135212](https://github.com/chrisgrieser/nvim-rip-substitute/assets/16150836/5a3a7bf6-6657-419f-b4c9-81c75b73f0f4)

### To Reproduce

- select text with visual mode or without selection
- press <leader>fs
- Typing in popup

ripgrep is present with pcre2 and jit

```
❯ rg --pcre2-version
PCRE2 10.42 is available (JIT is available)
```

### neovim version

```Text
0.10
```

**Comment by chrisgrieser** [comment]
Hmm, the only potential cause for this I can think of is that you haven't save your buffer to the file (`:w`).

If that is not the case, could you try a reproducible config? (Save as `repro.lua` and run with `nvim -u repro.lua`.)

```lua
local spec = {
	{
		"chrisgrieser/nvim-rip-substitute",
		opts = {}, -- insert config here
		keys = {
			{
				"gs",
				function() require("rip-substitute").sub() end,
				mode = { "n", "x" },
				desc = "rip substitute",
			},
		},
	},
}
--------------------------------------------------------------------------------
vim.env.LAZY_STDPATH = "./nvim-repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
require("lazy.minit").repro { spec = spec }
```

**Comment by c30ra** [comment]
that's it... i tried it in a non saved buffer to see if everything is working. On saved buffers it work. Thanks for the quick reply!!

**Comment by chrisgrieser** [comment]
no problem! Nonetheless, this bug report was still helpful. I made a small update that ensures the buffer is being written when rip-substitute is called, so that this issue should not occur again.

**Comment by c30ra** [comment]
It's not possible to pass directly the buffer content to rg? Maybe using echo? 
if i do: `echo some string | rg  --column --line-number --only-matching some`  it gets the results.

**Comment by chrisgrieser** [comment]
yeah, passing the buffer content as stdin is possible. But simply writing the buffer is a bit simpler code-wise than passing the buffer content around to stdin. (And it's also better performance-wise, since this plugins calls `rg` on every keystroke for the incremental preview, and iirc, `rg` has a caching mechanism for when repeatedly reading from the same file)

**Comment by chrisgrieser** [comment]
FYI / note for myself: I've changed it to indeed pass the buffer content from stdin, as reading from the file directly has the disadvantage of not being able to handle non-file buffer (e.g. editable quickfix lists from some plugins).

**Comment by c30ra** [comment]
Nice, I'll try it as soon as I will be back home!!
